db_master_ip:
db_master_port: 3306

db_slave_ip:
db_slave_port: 3306

backend_1_ip:
backend_1_port: 8100

backend_2_ip:
backend_2_port: 8101

load_balancer_ip:
load_balancer_port: 8001

frontend_ip:
frontend_port: 8000